# Generated by Django 3.1.1 on 2021-09-13 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(blank=True, choices=[('money market funds', 'MONEY MARKET FUNDS'), ('fixed income funds', 'FIXED INCOME FUNDS'), ('equity funds', 'EQUITY FUNDS'), ('balanced funds', 'BALANCED FUNDS'), ('index funds', 'INDEX FUNDS'), ('specialty funds', 'SPECIALTY FUNDS'), ('fund-of-funds', 'FUND-OF-FUNDS')], max_length=50)),
                ('fund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='portfolio.customer')),
            ],
        ),
    ]
